version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: igym_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: igym
    ports:
      - "5433:5432"
    networks:
      - igym-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - igym-network
networks:
  igym-network:
    driver: bridge
