spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/igym_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: f90ad10fe7c397
    password: sua_senha_completa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never