spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/igym_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:f90ad10fe7c397}
    password: ${MAIL_PASSWORD:sua_senha}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never